# Generated by Django 4.2 on 2023-05-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30, unique=True, verbose_name='nom')),
                ('tared', models.BooleanField(default=False, verbose_name='tarée')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='MasterBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI', models.CharField(max_length=20, unique=True, verbose_name='IMEI')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('GPS_latt', models.FloatField(default=0.0, verbose_name='Lattitude GPS')),
                ('GPS_long', models.FloatField(default=0.0, verbose_name='Longitude GPS')),
                ('bal_1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bal_1', to='balruche.balance')),
                ('bal_2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bal_2', to='balruche.balance')),
                ('bal_3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bal_3', to='balruche.balance')),
                ('bal_4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bal_4', to='balruche.balance')),
            ],
        ),
        migrations.CreateModel(
            name='BalRucheData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date_heure')),
                ('w_num', models.IntegerField(db_index=True, default=0, verbose_name='N° semaine')),
                ('d_num', models.IntegerField(db_index=True, default=0, verbose_name='N° jour')),
                ('humid', models.IntegerField(default=0, verbose_name='humidité (%)')),
                ('temp', models.IntegerField(default=0, verbose_name='température (°C)')),
                ('m1', models.FloatField(default=0, verbose_name='Masse ruche-1')),
                ('m2', models.FloatField(default=0, verbose_name='Masse ruche-2')),
                ('m3', models.FloatField(default=0, verbose_name='Masse ruche-3')),
                ('m4', models.FloatField(default=0, verbose_name='Masse ruche-4')),
                ('masterbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balruche.masterbox')),
            ],
        ),
    ]
