# Generated by Django 4.2 on 2023-04-19 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balruche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalRucheData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('humidity', models.IntegerField(verbose_name='humidité (%)')),
                ('temperature', models.IntegerField(verbose_name='température (°C)')),
                ('masse_ruche1', models.FloatField(verbose_name='Masse ruche-1')),
                ('masse_ruche2', models.FloatField(verbose_name='Masse ruche-2')),
                ('masse_ruche3', models.FloatField(verbose_name='Masse ruche-3')),
                ('masse_ruche4', models.FloatField(verbose_name='Masse ruche-4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
