# Generated by Django 4.2 on 2023-05-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balruche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbox',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='balruchedata',
            name='gay_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='N° jour'),
        ),
        migrations.AlterField(
            model_name='balruchedata',
            name='week_num',
            field=models.IntegerField(db_index=True, default=0, verbose_name='N° semaine'),
        ),
        migrations.AlterField(
            model_name='masterbox',
            name='IMEI',
            field=models.CharField(max_length=20, unique=True, verbose_name='IMEI'),
        ),
    ]
