# Generated by Django 4.2 on 2023-04-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balruche', '0002_balruchedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balruchedata',
            old_name='humidity',
            new_name='humid',
        ),
        migrations.RenameField(
            model_name='balruchedata',
            old_name='temperature',
            new_name='temp',
        ),
    ]
