# Generated by Django 4.2 on 2023-04-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balruche', '0003_rename_humidity_balruchedata_humid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
